### ISSUE TITLE
MongodExecutable.stop() never ends on Windows

### ISSUE THREAD

**Issue by loicmathieu** [flapdoodle-oss/de.flapdoodle.embed.mongo#373] opened 2022-02-09 14:15 UTC
Hi,

We have a working unit test on Linux that didn't work on Windows.

We're starting a database at the begining of the test then stopping it at the end via the `MongodExecutable.stop()` method.
On Windows, the test never ends and get killed by surefire after the timeout.

When killing, surefire takes a thread dump and here what we see:

```
Killing self fork JVM. Received SHUTDOWN command from Maven shutdown hook.
Thread dump before killing the process (5252@fv-az283-841):
"main" 
   java.lang.Thread.State: RUNNABLE
        at java.base@11.0.14/java.io.FileDescriptor.close0(Native Method)
        at java.base@11.0.14/java.io.FileDescriptor.close(FileDescriptor.java:297)
        at java.base@11.0.14/java.io.FileInputStream$1.close(FileInputStream.java:375)
        at java.base@11.0.14/java.io.FileDescriptor.closeAll(FileDescriptor.java:355)
        at java.base@11.0.14/java.io.FileInputStream.close(FileInputStream.java:373)
        at de.flapdoodle.embed.process.runtime.ProcessControl.closeIOAndDestroy(ProcessControl.java:89)
        at de.flapdoodle.embed.process.runtime.ProcessControl.stopOrDestroyProcess(ProcessControl.java:124)
        at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:145)
        at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:81)
        at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:77)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:196)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:119)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:174)
        at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:81)
        [... other frame in or code ...]
```

**Comment by paulboichat** [comment] 2022-03-10 16:05
I'm also seeing this (or a similar issue) - running openjdk 17 on windows 11. The test fails to complete with 

  16:01:25.299 [Test worker] DEBUG org.mongodb.driver.connection - Closing connection connectionId{localValue:1, serverValue:1}
    16:01:25.300 [Test worker] DEBUG org.mongodb.driver.connection - Closing connection connectionId{localValue:2, serverValue:2}
    16:01:25.308 [Test worker] DEBUG reactor.core.publisher.Hooks - Reset onEachOperator: micronaut
    16:01:25.316 [Test worker] DEBUG d.f.embed.mongo.AbstractMongoProcess - try to stop mongod
    16:01:25.436 [Test worker] INFO  d.f.e.process.runtime.ProcessControl - stopOrDestroyProcess: process has not exited

**Comment by paulboichat** [comment] 2022-03-10 17:31
Have managed to get the test to finish by deleting the temp extracted embeded mongo data directories forcing a redownload of mongo. Odd

**Comment by michaelmosmann** [comment] 2022-03-28 07:50
@paulboichat and now it works everytime?

**Comment by paulboichat** [comment] 2022-03-28 09:06
Yes it seems to. Consistently run the tests including the occasional failure and it's all fine. Only seems to have been a problem with the initial runs/setup.

**Comment by michaelmosmann** [comment] 2022-03-30 15:01
ok.. thanks for this feedback .. as i don't have any idea to reproduce this, the only thing i can do right now is to keep it in my mind. i will close this ticket.

**Comment by loicmathieu** [comment] 2022-03-31 07:20
The issue is still reproducible each time on our CI server running on Github Action.
Please, do not close my issue !

**Comment by michaelmosmann** [comment] 2022-03-31 09:54
@loicmathieu so the thread hangs in java.base@11.0.14/java.io.FileDescriptor.close0(Native Method)?

**Comment by loicmathieu** [comment] 2022-03-31 09:56
@michaelmosmann yes, it is what surefire reported

**Comment by Toshimichi0915** [comment] 2022-04-07 11:04
Altough I removed %USERPROFILE%\.embedmongo directory, the issue seems to persist.
Is there any workaround for this?

**Comment by Vovour** [comment] 2022-04-22 11:16
Hello, I had the same problem on Windows 10 after I increased `de.flapdoodle.embed.mongo` to version 3.0.0.
First I've used the workaround from @Toshimichi0915, but finally I could resolve the problem completely by using the latest version of `spring-integration-core` and `spring-integration-file` (currently the latest version is 5.5.10, previously I've used version 5.3.2.RELEASE).

**Comment by michaelmosmann** [comment] 2022-04-24 10:47
@Vovour so with this version it is working again? @Toshimichi0915 can you check this?

**Comment by Vovour** [comment] 2022-04-25 16:27
@michaelmosmann Yes, with this latest version of the metioned modules it works again, without the need for any other workarounds.

**Comment by loicmathieu** [comment] 2022-04-26 07:10
@Vovour is I understand correctly, it works with the last version of Spring framework not Flapdoodle MongoDB ?
So a workaround should have been done at Spring side.

**Comment by Toshimichi0915** [comment] 2022-04-26 08:58
I didn't use Spring at all however I had the issue. This is my build.gradle
```groovy
plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow'
}

dependencies {
    compileOnly project(':api')
    testImplementation project(':api')

    implementation 'earth2b2t:i18n-bukkit:2.0.0-SNAPSHOT'
    implementation 'fr.minuskube:netherboard-bukkit:1.2.2'
    implementation 'org.mongodb:mongo-java-driver:3.12.10'

    compileOnly 'com.destroystokyo.paper:paper-api:1.12.2-R0.1-SNAPSHOT'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7'
    compileOnly 'us.dynmap:dynmap-api:2.5'

    compileOnly 'org.projectlombok:lombok:1.18.22'
    testCompileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.22'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'

    testImplementation 'com.github.seeseemelk:MockBukkit-v1.18:1.24.1'
    testImplementation 'org.mockito:mockito-all:1.10.19'
    testImplementation 'com.google.jimfs:jimfs:1.2'
    testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.4.3'
}

test {
    useJUnitPlatform()
}

tasks {
    build.dependsOn(shadowJar)
}

shadowJar {
    relocate 'earth2b2t.i18n', 'earth2b2t.nations.i18n'
    relocate 'fr.minuskube.netherboard', 'earth2b2t.nations.netherboard'
}

```

**Comment by loicmathieu** [comment] 2022-04-27 07:04
I tested the latest version on my CI and it stills hang in Windows so the issue still occurs.

**Comment by michaelmosmann** [comment] 2022-05-17 18:25
@loicmathieu do you use windows as your working platform too? does it happens there too or only on your CI?

**Comment by loicmathieu** [comment] 2022-05-18 07:24
@michaelmosmann I cannot reproduce the issue on a Windows 10 laptop I have, it only happens on the CI.

**Comment by michaelmosmann** [comment] 2022-05-21 06:59
@loicmathieu puh.. hmm.. have to think about it

**Comment by tuckerpm** [comment] 2022-08-31 18:38
I'm having the same problem on a new laptop running Windows 10 Pro.

**Comment by michaelmosmann** [comment] 2022-09-07 16:07
@tuckerpm so do you have any logs/stacktraces?

**Comment by tuckerpm** [comment] 2022-09-07 16:49
Sorry, I don't.  I noticed some weird mongo processes still running after terminating the test so I rebooted the laptop and haven't had the problem since.

**Comment by michaelmosmann** [comment] 2022-09-08 15:25
@tuckerpm i know that this can happen if the test fails and there is no cleanup .. i tried to solve this issue with my latest refactoring: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/embed-mongo-4.x/Howto.md

**Comment by michaelmosmann** [comment] 2022-10-14 13:03
@tuckerpm @loicmathieu is this still an issue?

**Comment by tuckerpm** [comment] 2022-10-14 13:38
I haven't had this issues since rebooting.

**Comment by Toshimichi0915** [comment] 2022-10-14 14:11
Is there any reason to close the stream before calling Process#destroy? This seems like the easiest solution to be honest...

**Comment by michaelmosmann** [comment] 2022-10-15 07:45
ok.. so i close this.. reopen if problem is back again:)

**Closed by michaelmosmann** 2022-10-15 07:45 UTC
Labels: bug
