### ISSUE TITLE
Add support to Apple Silicon

### ISSUE THREAD

**Issue by ithkfrog** [flapdoodle-oss/de.flapdoodle.embed.mongo#335] opened 2021-02-13 04:01 UTC
I am using MacBook Air with M1 chip, when starting sprint-boot test with embed mongo the driver fail to detect correct version of architecture.

It downloads 32bit version instead of 64bit version, I do believe if it able to detect M1 as 64bit architecture Rosetta 2 should be able to run the driver correctly.

Below are the error logs:
`
Caused by: java.lang.IllegalArgumentException: this version does not support 32Bit: Version{4.0.2}:OS_X:B32
	at de.flapdoodle.embed.mongo.Paths.getBitSize(Paths.java:157) ~[de.flapdoodle.embed.mongo-2.2.0.jar:na]
	at de.flapdoodle.embed.mongo.Paths.getPath(Paths.java:97) ~[de.flapdoodle.embed.mongo-2.2.0.jar:na]
	at de.flapdoodle.embed.process.store.LocalArtifactStore.getArtifact(LocalArtifactStore.java:71) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.LocalArtifactStore.checkArtifact(LocalArtifactStore.java:38) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:65) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:113) ~[spring-boot-autoconfigure-2.4.2.jar:2.4.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.3.jar:5.3.3]
	... 110 common frames omitted
`

**Comment by Loki-Afro** [comment] 2021-02-13 07:39
closing as duplicate of #329

**Closed by Loki-Afro** 2021-02-13 07:39 UTC
