### ISSUE TITLE
Proxy values in Gradle systemProp.http.proxyHost .proxyPort and https variants being ignored.

### ISSUE THREAD

**Issue by quarky42** [flapdoodle-oss/de.flapdoodle.embed.mongo#537] opened 2024-08-14 17:42 UTC
**PROBLEM 1 - Error:**  `java.net.UnknownHostException: fastdl.mongodb.org`

Gradle 8.8 is properly configured to use the proxy.  Maven Dependencies / Gradle plugins all download properly. 
Using Eclipse-Temurin Java 17.0.11_9.

It seems to me that the system level proxy values defined in Gradle and in my environment are being ignored when I try and run these tests through Gradle.

I have these settings in my `~/.gradle/gradle.properties`:
```
systemProp.http.proxyHost = http-proxy.domain.ext
systemProp.http.proxyPort = 3128
systemProp.https.proxyHost = http-proxy.domain.ext
systemProp.https.proxyPort = 3128
```

I also have environment variables set:
```
http_proxy=https://http-proxy.domain.ext:3128
https_proxy=https://http-proxy.domain.ext:3128
```

I can see in the log output the URL that it is trying to download the zip file from.  When I place that url in the web browser, the zip file downloads manually with no problem.   So, I know the proxy is allowing the download.

**PROBLEM 2: SIMPLE manual downloading doesn't work**
I load that zip file in `~/.embedmongo/windows/` and re-run the flapdoodle based tests and get the same error message all over again.   The `~/.embedmongo/windows/` does not work as I've seen described online.

If I load the zip file and rename it to archive.zip to an extremely long hashed out path contained in the exception, THEN and only then am I able to get around this hostname lookup / proxy issue.

This is the absurdly long and awful path for the manually downloaded file to be placed in as recommended by the exception:
```
Caused by: java.lang.IllegalStateException: could not download https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-5.0.27.zip (if this issue persist, you can download it manually to C:\Users\REDACTEDUSER\.embedmongo\archives\https-fastdl-mongodb-org\56cb3d10404e5b9df5358ac4ee83efcb\windowsmongodb-windows-x86-64-5-0-27-zip\a490b11266924ba650400369c40347bf5aa8652b21f531f5b3c467862f457fdb\archive.zip
```
.embedmongo/windows and .embedmongo/win32 are better....  or if your'e taking ideas:  how about all manually downloaded zip files just get placed in .embedmongo/archive/     they shouldn't need to be sorted into different folders by OS.

My `build.gradle`:
I have both `de.flapdoodle.embed.mongo` and `de.flapdoodle.embed.mongo.spring3x` on my build.gradle file.  I have tried 4.15.0 (both)  and 4.16.2/4.16.1 (respectively)   I get the same behavior.
I just upgraded to Spring Boot 3.2.8 from 2.7.18, so this is my first time trying to get these versions downloaded.  We had been previously using Mongo 3.0.15 in the old version of Spring.

I am running with:
```
@TestPropertySource( properties = [ 'de.flapdoodle.mongodb.embedded.version=5.0.27' ] )
```
5.0.28 doesn't seem to be recognized by de.flapdoodle.embed.mongo.spring3x.   The error message shows a "5.0.28-rc0" among the versions it is looking for, but not a 5.0.28.    (there is no absurd recommended .embedmongo/archive/path/buried/in/a/ridiculous/number/of/subdirectories for manual extraction when I use 5.0.28, but if I change it to 5.0.27, I get the suggested path to place the archive.zip file.)

Top level exception:
[flapdoodle_error.txt](https://github.com/user-attachments/files/16616761/flapdoodle_error.txt)

I have tried running (gradle wrapper 8.8) `./gradlew :controller:test` with all of the various -Dhttp.proxyHost -Dhttp.proxyPort values set on the command line and I still get an unknown host exception.

I wish the documentation would clearly state what file(s) need to be extracted from the zip file and where exactly do those files need to be placed.   None of the manual download / zip file detection stuff is working as expected.

**Comment by quarky42** [comment] 2024-08-14 18:15
Update:

I got the existing failing tests to pass by removing:
`de.flapdoodle.embed.mongo` from the build.gradle so I only have the `de.flapdoodle.embed.mongo.spring3x` one

I also had to update my mongodb driver.   I started with 4.9.1.  I may go to 4.11.3 before trying to update to driver v5.

So, was the de.flapdoodle.embed.mongo conflicting with the de.flapdoodle.embed.mongo.spring3x?   Maybe I followed some erroneous Spring Boot 3.x Upgrade advice when adding both dependencies?

**Comment by quarky42** [comment] 2024-08-14 18:17
Do I need to do something in the unit test to bring the mongo database down?  Looks like it was left running in the background after the test passed.

**Comment by michaelmosmann** [comment] 2024-08-15 05:23
@quarky42 .. i will try to give some answers to the IMHO most important parts of this question:

The mongodb team decided some time back to revoke a simple download path version schema so one can not simply guess the path .. there is now a project dedicated to this part (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver). To avoid any problems from the past (partial downloaded files, changed archive name patterns etc) everything is hashed to avoid collisions. For the download the hash of the download url is used for storage, the extracted files are placed in a directory with the hash of the archive content..  that's what you get in the exception if the download failed. As the download is made by the jdk UrlConnections-code it should honour any platform proxy configuration. If you get "java.net.UnknownHostException: fastdl.mongodb.org" i guess its because this domain can not be resolved to an IP, which is needed even with an proxy inbetween (i guess, i would be surprised if not).

The base concept for this library after the latest refactoring is this: Each part of the Initialisation has a matching cleanup part. So if anything fails, there is a rollback of everything that succeeded so far. If there is still a running mongodb somewhere, it can only be the case if spring thinks that it should not kill itself. Maybe you should try @DirtyContext from this sample: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#test-isolation

**Comment by quarky42** [comment] 2024-08-15 14:46
My Gradle configuration successfully pulls down hundreds of dependencies on a very large project.

Out of that project, the only thing getting any kind of connection error is flapdoodle downloading the mongo binary. 

When I open Chrome or Firefox, both are able to download the zip file from the URL in the error log.  They use the same simple proxy server that gradle is successfully configured with.

The IP for https://fastdl.mongodb.org is clearly resolving everywhere outside of the flapdoodle dependency.

Only https urls are allowed through the proxy.  If the dependency was downloading over http, I would expect those to be unreachable.

When I look at the URLs of manual downloads from fastdl.mongodb.org I don't see any of the hashing.  I see pretty simple URLs that could be saved locally in a simpler directory for manual usage rather than making the user create a whole directory tree.

Flapdoodle was used in about 15 different places.  They were all failing after upgrading to a newer version of flapdoodle to support the newer Spring Boot 3.2.8.  The simplest SpringBootTest literally has a simple application startup and checks to make sure it started.  This simple test (one line spock test), ran by itself, was failing with same exception as in the log above.  The Spring Boot Application it was running was also pretty simple... A rest controller.

**Comment by michaelmosmann** [comment] 2024-08-16 04:52
@quarky42 .. hmm.. this is strange. I will have a look into this..

**Comment by quarky42** [comment] 2024-08-16 05:03
Thank you.  I don't know if it has an impact or not, but one detail that might impact this is the kind of proxy we're using. 

It is a Squid Proxy configured to be reached by the clients via http:// for both urls beginning with http:// and https://

There are a few URLs that are allowed through via http but most http traffic is blocked....so the majority of the rules are for allowing https:// based endpoints.

If I can get ahead on some work I need to do, I will try to come up with a minimal project that demonstrates the problem, but I am not sure how long this will take as I've got about 3 things on my plate I really need to get done.

Also, to reiterate, I did try running a single unit test with gradle and -D versions of those proxyHost and proxyPort configs, but there was no change in the behavior / error message.

**Comment by michaelmosmann** [comment] 2024-08-16 06:33
@quarky42 .. i think, i have everything i need to know:) i will inform you as soon as i have some updates..

**Comment by michaelmosmann** [comment] 2024-08-16 06:37
@quarky42 as environment variables are not used by the jvm and i am not sure if gradle propagates systemProp settings down to each test this might help:

java.net.useSystemProxies=true

I have tests that as i use the jdk url-connections https.proxyHost and https.proxyPort are used if set (no api change, only new tests for this case: https://github.com/flapdoodle-oss/de.flapdoodle.java8/commit/be3b8c1ed37c4c3bb1241fe563d729fa93835299 ) . 

You can check for the system property propagation inside of the test (System.getProperty(..)), but i would not expect that they are there.

**Comment by quarky42** [comment] 2024-08-17 00:52
Do I set this in gradle.properties?
`java.net.useSystemProxies=true`

Setting a system wide property that propagates the proxy into the tests themselves seems like the wrong direction to take.  I don't want my tests to use the proxy.  I want tools to be smart enough to go get the system proxy values themselves.

I would suggest that flapdoodle, as a dependency that acts as an auto downloader, should be doing a more robust job of looking for proxy settings rather than the developer having to embed proxy config in the project. 

We have a team of more than 20 developers on one of our projects.  6 of them are behind a proxy, and 14+ are not behind a proxy. Having proxy stuff embedded in the project instead of the developer's system config is an uphill battle with this team, and not one the 6 of us behind a proxy are going to win.

The 6 that are behind the proxy have some fairly standard settings:
gradle.properties has the already mentioned systemProp config for proxy settings.  This works for downloading all the other dependencies from Maven.
We have environment variables for http_proxy, https_proxy, and no_proxy.

Thank you for looking into this and considering the point of view. I will be reading this again when I'm at work to see what I can do with the info provided so far.

**Comment by quarky42** [comment] 2024-08-17 00:53
I think you have a minor copy / paste error on line 476 of the test you linked to.   That block appears to be targeting https, but the nonProxyHosts is being pulled from http proxy config.

**Comment by michaelmosmann** [comment] 2024-08-17 16:48
> I think you have a minor copy / paste error on line 476 of the test you linked to. That block appears to be targeting https, but the nonProxyHosts is being pulled from http proxy config.

Yeah.. no.. as the documentation states: The HTTPS protocol handler will use the same nonProxyHosts property as the HTTP protocol. (see https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html ) IMHO not the best idea.. but who am i.

**Comment by quarky42** [comment] 2024-08-17 16:49
Thank you.  I thought that was weird that they had two different values.  I gladly stand corrected and learned about something that has bugged me for a while.

**Comment by michaelmosmann** [comment] 2024-08-17 16:49
>  We have environment variables for http_proxy, https_proxy, and no_proxy.

Short answer for today: i think about some kind of solution.

**Comment by quarky42** [comment] 2024-08-17 22:21
> > We have environment variables for http_proxy, https_proxy, and no_proxy.
> 
> Short answer for today: i think about some kind of solution.

I understand. No pressure. I'm very thankful you're considering it.  Lots of things use http_proxy, https_proxy, and no_proxy environment variables so if you checked those directly it would be a very universal solution. 

Off the top of my head, many Linux applications and services support those variables in addition to Python, and NodeJS.

We Dockerize a lot of services into Linux based containers, so we add those to our container build-args so that the containers can get packages added, updated, modules downloaded, etc.

**Comment by michaelmosmann** [comment] 2024-08-18 07:28
@quarky42 I used the jdk http client to avoid any own solutions because they might not work as stable as wished. AFAIK the system properties are not propagated into forked processes so even if gradle has some properties set, the jvm which runs the tests does not have it. Using environment variables by default may lead to unwanted behaviour, so I think I will provide a property to enable the usage of the environment variables.

**Comment by quarky42** [comment] 2024-08-18 07:37
Roughly how do you envision this property being used by the developer? 

If the property exists in the development environment, good... People can choose to use this property without forcing people on a to spread out team at different locations to use it.

I'm not sure what unwanted behavior you could be imagining though... The whole purpose of http_proxy and related flags is to communicate to proxy aware applications how to reach the outside world. No one has http_proxy variables set that doesn't want them to be used by things.  The setting of those variables is already an active choice.   Plus if people want those values to be set only per command there is a way to do that.

**Comment by michaelmosmann** [comment] 2024-08-18 19:19
@quarky42 .. per default the http_proxy environment variable does not have any effect on the jdk http client.. if I detect and use information from this environment variables and someone has the system properties set (which are used inside the jdk code) they might not get the expected result if these information differ.. to avoid that I have to check for these system properties and emulate the jdk behaviour.. which sound easy but can be a source of trouble.. so i would check for an extra system property and use the environment variables if set (override any system property if set).

It's sounds like overkill, but as this library is downloaded each month by about 70.000 projects/people i would not take the risk.

**Comment by quarky42** [comment] 2024-08-18 20:02
In the default case where these manually set environment variables don't exist, there is nothing to worry about there.  These variables aren't automatically present.

In the case where a proxy is configured, the means to exclude flapdoodle from that proxy is a very strange edge case given the purpose of a proxy.  In that unusual edge case, the direct and standard solution that I would see across other applications that support proxy config is to use the "no_proxy" or nonProxyHosts for its intended job.

It would be very strange for someone to have a proxy configured and to not want flapdoodle to go through that proxy.  In that edge case, the standard approach is to use no_proxy.

Say you add an environment flag to enable loading proxy support.  Are you going to handle the case where proxy support is enabled but there is nothing configured on the system at that time?  You might be planning on making this a "no op" operation in that it just behaves like normal if there is no proxy config found and skips trying to load the non-existent settings.  That would certainly be okay.

One option that is worth a look is how many applications have a user config.  If you want a user config file in ~/.embedmongo where the proxy information can be set/loaded from, that would be very similar to how Gradle, Python, NPM, Yarn, and Git all do it.  It would certainly be a well understood choice to support a local config file.   Some of these applications support both config file based proxy settings and environment variable based settings.

The config file could be optional.  If there isn't one, defaults are used.  If the connection fails, the error message could say something like: "If a proxy is needed, add it to /path/to/.embedmongo/flapdoodle.config file with java based http[s].proxyHost= http[s].proxyPort= http[s].nonProxyHosts= values (one value per line)."

In the case of a config file is present, it would be used directly, no extra flag besides the proxy settings is necessary. The user has actively stated in the config what they want used and amounts to a one-time setup for their environment.

Thank you for allowing me to discuss this further. I hope you don't mind the brainstorming here and the comparison to other tools. I very much appreciate how many things use a common approach (or 1 of 2 common approaches if they only support one option).

Personally I prefer applications that pickup the environment variables because that is one less step I have to do in order to get a new user on the project going with it, but a flapdoodle config file that uses java standard syntax would not be a problem.

**Comment by michaelmosmann** [comment] 2024-08-19 06:01
@quarky42 funny thing: this issue is reported in the jdk and unresolved since at least 2004 (with the latest "update" here: https://bugs.openjdk.org/browse/JDK-8292530 )

**Comment by michaelmosmann** [comment] 2024-08-22 19:24
@quarky42 there is a new release of de.flapdoodle.embed.mongo (4.17.0). I did link the different ways to customize a proxy here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-proxy-for-download .. and here is how you enable http_proxy environment variable support: https://github.com/flapdoodle-oss/de.flapdoodle.java8/blob/master/docs/URLConnections.md#enable-env-variable-httpproxy-detection

**Comment by quarky42** [comment] 2024-08-23 14:30
Thank you.  I'll be using the system property option.   So, seems like I should be able to set this property in Gradle's ~/.gradle/gradle.properties file?

`de.flapdoodle.net.useEnvProxySelector=true`

I will try it today or Monday.  Running out of hours for the week.  Thanks a lot for looking into this.

**Comment by michaelmosmann** [comment] 2024-08-24 06:17
@quarky42 there are two ways to do that.. see first answer to this question: https://stackoverflow.com/questions/21406265/how-to-give-system-property-to-my-test-via-gradle-and-d

**Comment by quarky42** [comment] 2024-08-24 16:59
If I can use this or something similar if my syntax isn't quite right I in my ~/.gradle/gradle.properties file:  
`systemProp.de.flapdoodle.net.useEnvProxySelector=true`
Or
`de.flapdoodle.net.useEnvProxySelector=true`

Then that will work nicely.  I cannot add anything dev environment related to the project itself without a lot of work because we have 20+ developers and at least 4 different environments that our project is built on.  Frankly, environment tailoring belongs in the environment and not in a large shared project. 

I may be misinterpreting your response.  In my experience I do currently and should be able to specify environment level properties in the user's gradle.properties file as it is not useful to have to enter these in manually. We already do this, so that is why I expect to be able to set the property at the per user level and flapdoodle should hopefully be able to find it.

The large 30+ micro service project we have is building, testing, and running just fine on all these environments with a mix of Java/SpringBoot, Gradle, JavaScript/REACT with Jest unit tests via NodeJS, Python, and Docker.  All of these things work correctly with the developers that have proxies and with the devs that do not have proxies without adding anything environment specific to the project because all of these mature technologies include proper full proxy support.  We do have to have some values defined in our environment variables, some get defined in that gradle.properties for Java.

If I can't place something in my user level gradle.properties or elsewhere in my environment  to make this work, then there is something unclear in the use case / user level interaction.

We have a number of simple values defined in our gradle.properties for managing per-user config items like login tokens, urls, and other things.  So I'm already familiar with defining values here to a degree.  What I am not sure of from your response is whether or not flapdoodle will use the values set there or not. 

Properties defined in the user's gradle.properties file are absolutely accessible in the project so I don't see why flapdoodle wouldn't be able to use these values when defined one way or the other presented above.  I hope to test it next week, but if you understand what I am scrutinizing and are willing to comment on the specific question of whether or not flapdoodle will respect one of the two gradle properties above, I would be very much be interested in the confirmation. 

Thank you for your time.  I hope the use case is clear in that we cannot set any proxy info in the project itself and manually entering proxy information on the command line is a nonstarter.   With the number of people and the size of this project, I hope you can also see that there will be many different IDEs involved, some command line usage.... It needs to work under multiple scenarios.  So, setting a property in gradle.properties is ideal here. 

I'm sorry this is long.  It's the best I can do to try and make my thoughts clear.

**Comment by michaelmosmann** [comment] 2024-08-25 05:19
@quarky42 if it works already the way you use the gradle.properties file its fine for me.. as there is more than one way to do things with gradle someone solved the system-property-in-tests problem already .. you can test if this works as expected if you check inside of a unit test for this system property .. the rest, checking for the environment variables should work then..

**Comment by quarky42** [comment] 2024-08-26 23:02
I was able to get the new environment proxy support working. Thank you.

I had to move the old spring6x 4.16.1 dependency below the newer embed.mongo as the older spring6x was being found first and it was throwing an error about not being able to reach the host.  Once I removed that, the different versions of mongod downloaded nicely.  (I changed the 5.0.27 to some other versions that I didn't have and made sure that it worked.)

Is this change going to be considered for addition to the spring variants?

I will leave you with one suggestion:   Please consider adding a detection  whether or not flapdoodle is being downloaded with Gradle/Maven.   If flapdoodle is being downloaded with Gradle or Maven, then please just use the same proxy that Gradle or Maven is using.   I already have systemProp.http and systemProp.https host and port proxy values set in my Gradle configuration in order to download all the other dependencies.   Since flapdoodle itself is a dependency downloader of sorts (at least at the beginning) having it support the same proxy values that Gradle or Maven support would be a lot nicer than having to have a dedicated setting for it.   For anyone that doesn't want flapdoodle to be proxy aware, having a property that can be set to "opt out" of that support is also nice to have the choice.

For anyone else seeking to use this 4.17.0 with Gradle, Spring Boot, and proxy support for flapdoodle, these are the changes I made from a much older version:

**~/.gradle/gradle.propertes:**
`de.flapdoodle.net.useEnvProxySelector=true`

**Project build.gradle:**
`testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:4.17.0'`
`testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring26x:4.16.1'`

**Project src test class:**
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestPropertySource(properties = ['de.flapdoodle.mongodb.embedded.version=5.0.27'])
```
This particular SprintBootTest didn't need the WebEnvironment.   I'm just showing where the TestPropertySource was added.  To some of my tests I did need to add some mongodb configuration

**Comment by michaelmosmann** [comment] 2024-08-27 06:10
@quarky42 i will make a new release of embed.mongo.spring26x etc soon so that you only need the spring dependency if you are using spring.

To make this new behavior a default i would risk to change the behavior in existing projects. There are so many different setups out there that tracing the way from the problem to the cause is already time consuming .. so i prefer to change as little as possible. And this is the first step.. the next step could be something like detecting the existence of http_proxy env variable and system property and to give a hint how to get rid of one of these.. 

Anyway.. thanks for your patience and input:)

**Comment by quarky42** [comment] 2024-08-27 14:14
I understand where you're coming from and I appreciate the chance to discuss it.  As a developer one of the most frustrating things I deal with is software not following accepted standards and doing something different from everything else in the same realm.

This update you made is absolutely a step in the right direction.  I get that you're risk adverse and don't want to cause problems for others 

Doing a search on some of the connection error messages that are given through different versions of flapdoodle, you would see that there are more people that have problems because of the lack of proxy support. 

Detecting the environment variables and giving the developer an error message that explains what to turn on would be incredibly helpful. Thank you for considering that.  I noticed logic similar to that in newer versions of flapdoodle for other missing config options and very much appreciated the effort that went into making information in the error part of the solution.

**Comment by michaelmosmann** [comment] 2024-08-27 16:31
@quarky42 i close this issue with the release of the matching spring versions.. :) thanks..

**Comment by michaelmosmann** [comment] 2024-11-26 19:02
release done..

**Closed by michaelmosmann** 2024-11-26 19:02 UTC
