### ISSUE TITLE
Wrong URL for MacOS/OSX download

### ISSUE THREAD

**Issue by VitaliyKulikov** [flapdoodle-oss/de.flapdoodle.embed.mongo#359] opened 2021-12-07 09:55 UTC
Currently, i have issue with running Spring Boot application with embedded database. Version: `de.flapdoodle.embed:de.flapdoodle.embed.mongo -> 3.0.0`

`active`
```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-5.0.5.tgz
``` 
`expected`
```
https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-5.0.5.tgz
```

**Comment by hjaved-nha** [comment] 2021-12-08 09:23
Same for Linux (ubuntu etc)

**Comment by infoShare** [comment] 2021-12-08 11:13
For windows it's the same.
It's impossible to select MongoDB 4+ which will work on linux and windows at the same time.

**Comment by mraible** [comment] 2021-12-10 01:15
I can confirm that using `3.5.5` solves the problem for me.

**Comment by ksmilek-wr** [comment] 2021-12-16 13:16
I suppose that issue is here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/4e9ffbe26f02d0560d8d9e4ab73f3aca0f399681/src/main/java/de/flapdoodle/embed/mongo/Paths.java#L105
Path was probably changed by remote server and thats why it does not work anymore

**Comment by michaelmosmann** [comment] 2021-12-19 21:43
@ksmilek-wr do you still have this issue? You must use the new release if you want to use any newer mongodb version? the old way (link to Paths) does not work with any new mongodb version...

**Comment by oliverlockwood** [comment] 2021-12-31 10:43
From looking at some of the links generated by https://www.mongodb.com/try/download/community, I believe this affects all versions of MongoDB >= 4.2.x.

Here are some of the URLs:
- https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.6.23.tgz
- https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.27.tgz
- https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.2.17.tgz
- https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.11.tgz
- https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-5.0.5.tgz

@michaelmosmann what is the first version of embedded-mongo which will handle this?  I ask, because then we could raise a ticket against Spring-Boot, which currently (as of Spring-Boot 2.6.2, the latest at time of writing) manages the version of embedded-mongo to 3.0.0.

**Comment by michaelmosmann** [comment] 2022-01-02 15:11
@oliverlockwood current release is 3.2.5 which should work with spring boot 2.6.2.

**Comment by jgriff** [comment] 2022-01-06 18:41
I can also confirm latest spring boot `2.6.2` with `--spring.mongodb.embedded.version=3.4.23` renders the correct dl url.

Another coming complication will be multi-arch for apple M1, which will require Mongo (as well as the rest of the internet) to start shipping `linux/arm64/v8` variants.  And then downstream support here to recognize it and adjust the dl url accordingly.  However, Rosetta 2 seems to be doing an ok job with the `x86_64` so far for me.  YMMV

**Comment by derekdata** [comment] 2022-01-09 13:44
It seems for older versions of Mongo, the URL has changed.  Downloads are available here: https://www.mongodb.org/dl/osx

**Comment by michaelmosmann** [comment] 2022-01-09 19:08
@jgriff M1: this will be fun .. no.. i think this will be some kind of new pain ..maybe.. until there is a way to detect M1 somehow and mongodb will provide some special download for that it should work somehow..

**Comment by michaelmosmann** [comment] 2022-01-09 19:09
@derekdata does the current version not work for you? is there something missing?

**Comment by miroslavvojtus** [comment] 2022-01-13 12:30
I have tested with version flapdoodle:3.2.7 and mongodb:4.4.11 but now it fails with a following:
> Caused by: java.lang.IllegalArgumentException: windows distribution not supported: GenericFeatureAwareVersion{4.4.11}:Platform{operatingSystem=Windows, architecture=X86_64}

**Comment by infoShare** [comment] 2022-01-13 13:03
@miroslavvojtus Could you please check mongodb 4.4.9 if that's ok? 
I see that 4.4.11 it not supported.
...
V4_4_1(...),
V4_4_5(...),
V4_4_9(...),
V5_0_2(...),

**Comment by miroslavvojtus** [comment] 2022-01-13 20:01
Thanks for the hint @infoShare. I will check it tomorrow.
How and where did you find the suported versions list?

**Comment by infoShare** [comment] 2022-01-13 21:14
I've found it on the source code @miroslavvojtus on Version class.

**Comment by miroslavvojtus** [comment] 2022-01-14 07:06
Thanks @infoShare for the info.
For the others here is the link to the mentioned class: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java

**Comment by miroslavvojtus** [comment] 2022-01-14 07:25
I can confirm that flapdoodle:3.2.7 and mongodb:4.4.9 works together.

**Comment by giovanniberti** [comment] 2022-05-16 12:57
Is there any progress on this issue? The only version I managed to get working is `3.4.24`, which is pretty old :(

**Comment by michaelmosmann** [comment] 2022-05-17 18:03
@giovanniberti .. as i don't have any access to an mac (with or without an m1 cpu) i can not realy solve this issue by myself .. 

can you give me some summary what you already tried?

**Comment by giovanniberti** [comment] 2022-05-18 09:20
I was getting the same errors about the wrong link format (on x86-64). I retried today with version `3.4.5` and embedded mongo version set to `5.0.6` and everything worked fine 😃

P.S.: May I suggest to include possible valid versions when setting a non-supported version? (e.g. 5.0.8) I had to check as in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/359#issuecomment-1012832865 to get a valid version number :)

**Comment by michaelmosmann** [comment] 2022-05-21 06:57
@giovanniberti .. there is an issue how spring tried to integrate this project .. which already led to some confusion.. i will have a look into this .. maybe i can give some hints (log message, exception) for this kind of situation

**Comment by giovanniberti** [comment] 2022-05-23 13:21
Yeah, even a list of possible versions inside an exception message would go a long way 🙂

**Comment by michaelmosmann** [comment] 2022-05-23 15:44
@giovanniberti you might use my new integration projects (see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#spring-integration ) which don't have this version issue .. it should works as an replacement.

**Comment by toolforger** [comment] 2022-08-03 08:07
@michaelmosmann The given link leads to a page that links to a SNAPSHOT version for 2.6.
Since I can't use SNAPSHOT, I tried `de.flapdoodle.embed;de.flapdoodle.embed.mongo.spring:1.1.0-spring26x` but that requires legacy classes from the MongoDB driver and it's unclear which of the many MongoDB jars is the correct one.

If we can't get this to work we'll have to replace embedded mongo with a mock, and accept the loss in test quality even though we'd hate having to do that.

**Comment by michaelmosmann** [comment] 2022-08-08 15:18
@toolforger which springversion do you use?

**Comment by michaelmosmann** [comment] 2022-08-08 15:19
@toolforger see https://search.maven.org/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo.spring27x

**Comment by toolforger** [comment] 2022-08-08 16:30
That was 2.6.
Note that the issue can be fixed by either removing the links for 2.5 and 2.6, or updating the referenced pages with production-ready links.

Just as a data point: Our team would happily upgrade to either 2.6 or 2.7 (the preference for 2.6 isn't really strong).
Other teams might be forced to use 2.6, so I guess there's value in doing a 2.6 build.
I can't say whether 2.5 is of interest to anybody anymore. (Probably yes, given the way many teams operate, but that doesn't give you much information whether you should build a 2.5 release. Just that if you don't, I recommend either removing the link, or replacing it with a hint that you'll create something on request.)

Thanks for the offer though, much appreciated!

**Comment by toolforger** [comment] 2022-08-08 16:32
Hmm... the Maven Search link gives me 4.0.beta and 1.1.1 - which one would be the right one, integrating cleanly with Spring Boot (2.7)?

**Comment by michaelmosmann** [comment] 2022-08-09 15:50
@toolforger ok.. so i try to enhance 2.6 and 2.7 .. 
about the two versions: 
* 1.1.1 is more or less the configuration code from the spring project ported to my repositiory and with some bugs fixed.
* 4.x.x uses a rewrite of embed mongodb .. it should be a lot easier to make the changes there.. 

.. if i have finished it, i will write an comment in this ticket:)

**Comment by toolforger** [comment] 2022-08-10 06:59
Eventually, mention that you're using their code, with bug fixes.
It gives your users an intuition about what's in scope of your code and what isn't.
(That mention of "disable this Spring Boot configuration class" raised my eyebrows because I didn't know what the reasoning was; now that I know your reasons, I'm feeling much more confident in what's happening. Thanks!)

**Comment by michaelmosmann** [comment] 2022-08-15 09:30
@toolforger ah..yes.. you are right:) i will add some hints about that

**Comment by michaelmosmann** [comment] 2022-08-15 09:37
@toolforger
If you want to stay with spring 2.6 you can use:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x - stable version
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x--embed-mongo-4.x - refactored version

.. or 2.7:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x - stable version
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x--embed-mongo-4.x - refactored 

Maybe this is relevant too: 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/spring-2.7.x/HowTo.md#test-migration

**Comment by toolforger** [comment] 2022-08-15 11:28
The "HowTo" link on https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x looks like it is a subtitle but the text is missing. (Problem with that is that people tend to "see through" subtitles and tend to scan the text block below the subtitle to see if there's anything relevant in it; the strategy works well on the vast majority of web pages, but putting the link into the title defeats it.)

Suggestion: Instead of HowTo, write "Usage" (as normal text, not link), and add this paragraph (or a similar one, I'm probably getting details wrong):

Spring integration is the same for all versions of Embedded Mongo, see [here](http://example.com)

**Comment by michaelmosmann** [comment] 2022-08-15 11:37
@toolforger thanks for your input.. i was busy just to put everything together but your suggestion are a big improvment:)

**Comment by stefanbethke** [comment] 2022-09-08 07:31
I'm still having issues with the most current released version 3.4.8 on macOS:
```
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.4.16.tgz with proxy Optional.empty
```

The correct filename would be mongodb-macos-x86_64-4.4.16.tgz; this appears to be the case for all mongodb versions starting with at least 4.2.

**Comment by stefanbethke** [comment] 2022-09-08 08:00
Looking at the code in de.flapdoodle.embed.mongo.Paths, I feel it would be beneficial overall to be able to supply the download URL for a specific version and platform through either a simple configuration class or by setting properties. Using properties would help with configuring a local mirror and/or a filesystem cache in CI pipelines, I feel.

The documentation for DownloadConfigBuilderCustomizer does not make it easy to figure out how to provide something like this.

**Comment by stefanbethke** [comment] 2022-09-08 16:17
Sorry, I had a dependency snafu, and instead of 3.4.8 as specified in the POM, another dependency downgraded that to 3.0.0. So completely false alarm, all working as expected now.

**Comment by michaelmosmann** [comment] 2022-09-08 16:22
@stefanbethke ah..ok:) so i close this issue..

**Closed by michaelmosmann** 2022-09-08 16:22 UTC
Labels: waiting_for_reply, spring-integration-problem
