### ISSUE TITLE
FileUtils exception when shutting down flapdoodle embedded mongo

### ISSUE THREAD

**Issue by codecheetos** [flapdoodle-oss/de.flapdoodle.embed.mongo#116] opened 2015-03-24 23:38 UTC
Running my server with spring-boot. During integration-test, I run tests to upload zip files in gridfs. Works fine. But during shutdown (after all tests pass), get this annoying exception. Not sure what it tries to delete.

In my application code, I have commons-io:commons-io:1.1 dependency but this error might be coming from within embedded mongo and not my app. Suggestions?

eption in thread "Thread-4" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
    at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
    at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:91)
    at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:151)
    at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:94)
    at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:171)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    ... 6 more

**Comment by michaelmosmann** [comment] 2015-03-25 06:35
It looks like a classpath problem...
On shutdown we delete all temporary files (db files, mongo exe) ...

**Comment by codecheetos** [comment] 2015-03-28 21:16
Couldn't resolve this yet. Does this happen when using gridfs Apis to
upload files or just using embedded mongo for cleanup of stored documents?

I exported commons-io as application's pom dependency but did not work.
Does the jar need to be in environment class path? What point in junits
lifecycle does embedded mongo clean up? Don't see this error during mvn
clean install. Only during mvn integration-test.

Any suggestions welcome.

**Comment by michaelmosmann** [comment] 2015-03-29 09:40
> or just using embedded mongo for cleanup of stored documents?

On test shutdown, embedded mongo tries to delete all temporary files mongodb left.

> Don't see this error during mvn clean install. Only during mvn integration-test.

Your integration tests do not run on mvn clean install. You need this dependency in your module where the integration tests are located. You need this dependency only for tests, so the scope should be "test".

Can you show your pom.xml?

**Comment by ferrarimarco** [comment] 2015-06-12 16:41
Same issue here...
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
	at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:91)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:151)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:94)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:171)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 6 more
Fri Jun 12 18:38:53 dbexit: really exiting now
[mongod output] 
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
	at de.flapdoodle.embed.mongo.MongodProcess.deleteTempFiles(MongodProcess.java:92)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.cleanupInternal(AbstractMongoProcess.java:116)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:167)
	at de.flapdoodle.embed.process.runtime.AbstractProcess$JobKiller.run(AbstractProcess.java:238)
	at java.lang.Thread.run(Thread.java:744)

**Comment by michaelmosmann** [comment] 2015-06-12 18:41
..hmm ... .maybe a commons dependency version conflict... 

Am 12. Juni 2015 18:41:25 MESZ, schrieb Marco Ferrari <notifications@github.com>:
>Same issue here...
>java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
>	at
>de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
>	at
>de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:91)
>	at
>de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:151)
>	at
>de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:94)
>	at
>de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:171)
>	at java.lang.Thread.run(Thread.java:744)
>Caused by: java.lang.ClassNotFoundException:
>org.apache.commons.io.FileUtils
>	at
>org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
>	at
>org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
>	at
>org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
>	at
>org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
>	... 6 more
>Fri Jun 12 18:38:53 dbexit: really exiting now
>[mongod output] 
>Exception in thread "Thread-6" java.lang.NoClassDefFoundError:
>org/apache/commons/io/FileUtils
>	at
>de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
>	at
>de.flapdoodle.embed.mongo.MongodProcess.deleteTempFiles(MongodProcess.java:92)
>	at
>de.flapdoodle.embed.mongo.AbstractMongoProcess.cleanupInternal(AbstractMongoProcess.java:116)
>	at
>de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:167)
>	at
>de.flapdoodle.embed.process.runtime.AbstractProcess$JobKiller.run(AbstractProcess.java:238)
>	at java.lang.Thread.run(Thread.java:744)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/116#issuecomment-111551936

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matlockx** [comment] 2015-06-14 07:08
hi guys,

please provide you pom files, otherwise it's hard to figure out whether it might be a dependency version conflict or not.

thx

**Comment by ferrarimarco** [comment] 2015-06-14 13:15
Here you are, thx: https://github.com/ferrarimarco/is-web-app/blob/master/pom.xml

**Comment by logicaleak** [comment] 2015-06-15 15:40
I am having the same issue

**Comment by tvaughan77** [comment] 2015-06-30 19:30
FWIW, I started having this issue too, after adding a dependency on dropwizard-guice to my pom.  I narrowed it down to one of these dependencies:

```
  1 > [INFO] +- com.hubspot.dropwizard:dropwizard-guice:jar:0.8.1.0:compile
  2 > [INFO] |  +- com.google.inject:guice:jar:4.0:compile
  3 > [INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
  4 > [INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
  5 > [INFO] |  +- com.google.inject.extensions:guice-servlet:jar:4.0:compile
  6 > [INFO] |  +- com.squarespace.jersey2-guice:jersey2-guice:jar:0.10:compile
  7 > [INFO] |  |  +- com.google.inject.extensions:guice-multibindings:jar:4.0:compile
```

Then I realized I was using the old plugin version:
```
                    <groupId>com.github.joelittlejohn.embedmongo</groupId>
                    <artifactId>embedmongo-maven-plugin</artifactId>
                    <version>0.1.12</version>
```

After upgrading to this, it started working again with my guice dependencies
```
                    <groupId>de.flapdoodle.embed</groupId>
                    <artifactId>de.flapdoodle.embed.mongo</artifactId>
                    <version>1.48.0</version>
```

**Comment by tvaughan77** [comment] 2015-11-02 17:58
Follow up for anyone out on the internet who experiences this issue:  my previous answer about "just upgrading" is wrong;  the underlying cause was a guice misconfiguration within a server that was being IntTested with the embedded mongo!

If you get a failure related to class-not-found-exception, make sure your server is wired up correctly!

**Comment by avi613** [comment] 2017-01-26 22:00
+1

Here is my [pom](https://github.com/avi613/experiments/blob/master/poc-mongo/pom.xml)

And the full stask:

[mongod output] 2017-01-26T22:58:37.595+0100 I CONTROL  [conn3] now exiting
[mongod output] 2017-01-26T22:58:37.595+0100 I CONTROL  [conn3] shutting down with code:0
[mongod output] 2017-01-26T22:58:37.595+0100 I CONTROL  [initandlisten] shutting down with code:0
[mongod output]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.155 s
[INFO] Finished at: 2017-01-26T22:58:37+01:00
[INFO] Final Memory: 23M/395M
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: de/flapdoodle/embed/process/extract/ExtractedFileSets
        at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: de.flapdoodle.embed.process.extract.ExtractedFileSets
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 5 more

**Comment by joelittlejohn** [comment] 2017-03-14 14:29
@michaelmosmann @matlockx There are some fundamental issues with using shutdown hooks in Maven. There's a good explanation here:

http://maven.apache.org/plugin-developers/common-bugs.html#Using_Shutdown_Hooks

and a few instances of shutdown hooks affecting Maven plugins:

* https://github.com/joelittlejohn/embedmongo-maven-plugin/issues/44
* https://github.com/eclipse/jetty.project/issues/537
* https://issues.jboss.org/browse/JBASMP-61

Do you think you could find an alternative strategy that could replace the shutdown hook here?

**Comment by michaelmosmann** [comment] 2017-03-14 18:08
I think we can solve this by using java8 fileio stuff:) thanks for the hint.

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 14. März 2017 3:30:03 nachm. schrieb Joe Littlejohn 
<notifications@github.com>:

**Comment by Loki-Afro** [comment] 2017-03-16 11:13
Is this gh-171 related too?

**Comment by joelittlejohn** [comment] 2017-03-16 12:22
@Loki-Afro I think that depends on exactly what @michaelmosmann is suggesting.

@michaelmosmann are you suggesting removing the shutdown hook altogether or simply replacing the use of commons-lang FileUtils with some core Java 8 class?

If the shutdown hook is still present then I think #171 will remain a problem. That issue appears to occur when shutdown begins before the hook is even registered.

Over at https://github.com/joelittlejohn/embedmongo-maven-plugin/issues/44 we've seen two different exceptions in the log:

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: de/flapdoodle/embed/process/extract/ExtractedFileSets
        at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: de.flapdoodle.embed.process.extract.ExtractedFileSets
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 5 more
```
and
```
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:119)
        at de.flapdoodle.embed.mongo.MongodProcess.deleteTempFiles(MongodProcess.java:92)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.cleanupInternal(AbstractMongoProcess.java:124)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:172)
        at de.flapdoodle.embed.process.runtime.AbstractProcess$JobKiller.run(AbstractProcess.java:243)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 6 more
```

So we need to consider that in a shutdown hook, even files from *this project* may not be resolvable if they have not been loaded in the past.

**Comment by joelittlejohn** [comment] 2017-03-16 12:23
Basically, if we can find a way to remove the shutdown hook entirely then that would be great. If that's not possible then writing hooks with no other dependencies (either on classes in the same project or classes of external libraries) would help I think.

**Comment by Loki-Afro** [comment] 2017-03-16 12:26
@joelittlejohn but this affects more than just some file clean up mechanism, `JobKiller` is also a `ShutdownHook`.

**Comment by joelittlejohn** [comment] 2017-03-16 12:33
@Loki-Afro I don't follow what you are getting at.

The problem here is that when using Maven, the classpath may not be in a valid state to resolve new classes during a shutdown hook. The problem in #171 is that a if a shutdown hook is added too late, the shutdown process may have already started.

If we remove shutdown hooks from this project (and find alternatives) then this issue #116 and #171 will be fixed. If we keep the shutdown hooks and implement them differently to avoid class loading issue, #171 will remain unsolved.

**Comment by Loki-Afro** [comment] 2017-03-16 12:36
@joelittlejohn  I got you but this needs to get fixed too: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/09a5f51a0178e7e688bd3580488f02a368541488/src/main/java/de/flapdoodle/embed/process/runtime/AbstractProcess.java#L110

**Comment by LeeBear35** [comment] 2019-08-02 16:47
Has there been a resolution to this issue. I and a colleague both receive the message as the embedded MongoDB shuts down: embed.process.io.file.Files          : could not delete...
Checking the folder there is a wiredtiger.lock file that cannot be deleted by my user id or a local admin user on Windows 10.

Have not found what creates the file and how the permissions on that file are wired that it cannot be deleted.

**Comment by hfxy1981** [comment] 2021-07-14 03:37
Is there any update about this issue?

**Comment by michaelmosmann** [comment] 2021-11-07 19:11
There is a new release.. can you try if this solves your problem?

**Comment by michaelmosmann** [comment] 2022-10-17 05:33
if this is still an issue, please reopen...

**Closed by michaelmosmann** 2022-10-17 05:33 UTC
Labels: waiting_for_reply
