### ISSUE TITLE
Possible to use mongo 5 with Ubuntu 24.04.1 LTS?

### ISSUE THREAD

**Issue by MichielDx** [flapdoodle-oss/de.flapdoodle.embed.mongo#542] opened 2024-10-09 08:36 UTC
According to the [support matrix](https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support-matrix) it is not possible to use mongo, but I can use 4.0.12, which also isn't support for Ubuntu 24.

Is it somehow possible to use flapdoodle with mongo 5 on Ubuntu 24?

I'm using flapdoodle version 3.5.4.

Thanks!

**Comment by michaelmosmann** [comment] 2024-10-09 11:20
@MichielDx Can you upgrade to the latest version of flapdoodle? Do you have any error message?

**Comment by MichielDx** [comment] 2024-10-09 13:02
@michaelmosmann Unfortunately this is not that straightforward, since we are manually configuring and starting the db.

`public InMemoryMongo() {
        Command command = Command.MongoD;
        RuntimeConfig runtimeConfig = Defaults.runtimeConfigFor(command)
                .processOutput(ProcessOutput.builder()
                        .output(Processors.logTo(LOGGER, Slf4jLevel.INFO))
                        .error(Processors.logTo(LOGGER, Slf4jLevel.ERROR))
                        .commands(Processors.logTo(LOGGER, Slf4jLevel.INFO))
                        .build())
                .artifactStore(Defaults.extractedArtifactStoreFor(command)
                        .withDownloadConfig(Defaults.downloadConfigFor(command)
                                .artifactStorePath(new FixedPath("/tmp/embeddedMongodb"))
                                .build())
                        .withExtraction(DirectoryAndExecutableNaming.builder()
                                .directory(new FixedPath("/tmp/embeddedMongodb/extracted"))
                                .executableNaming(new NoopTempNaming())
                                .build()
                        )
                ).build();

        MongodStarter starter = MongodStarter.getInstance(runtimeConfig);

        final ImmutableMongodConfig.Builder mongodConfigBuilder = MongodConfig.builder()
                .net(new Net("127.0.0.1", PORT, false));
        mongodConfigBuilder.version(Version.V3_6_5);
        MongodConfig mongodConfig = mongodConfigBuilder.build();

        mongodExecutable = starter.prepare(mongodConfig);
        try {
            mongodExecutable.start();
        } catch (Exception e) {
            LOGGER.warn("Failed to start in Memory mongo DB - probably because previous instance was not shutdown due to Spring context caching.", e);
            mongodExecutable.stop();
            mongodExecutable = null;
        }
    }`

**Comment by michaelmosmann** [comment] 2024-10-10 06:09
@MichielDx it should be easy to rewrite this from scratch: see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo?tab=readme-ov-file#howto and start with "Basics" and "Customizations" .. if any questions, please just ask.

**Comment by MichielDx** [comment] 2024-10-10 10:30
I managed to rewrite it, so I'm now on version 4.17.0. When I try to use Main.V5_0, I get the same error as described here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/467

**Comment by michaelmosmann** [comment] 2024-10-10 11:28
@MichielDx try to use something newer like 7.x.x ..

**Comment by michaelmosmann** [comment] 2024-10-11 05:52
@MichielDx The Problem is this: the older mongodb uses libssl1.x .. but newer ubuntu version does not have this version anymore.. so you must decide: newer mongodb version or older ubuntu version.. you can not have both (or you find a way to install libssl1.x somehow).

**Comment by MichielDx** [comment] 2024-10-11 06:07
No problem, thank you!

**Comment by michaelmosmann** [comment] 2024-10-11 06:32
@MichielDx your welcome.. so i close this issue. Reopen if needed.

**Closed by michaelmosmann** 2024-10-11 06:32 UTC
