### ISSUE TITLE
IOException: Cannot run program "": error=13, Permission denied

### ISSUE THREAD

**Issue by poznachowski** [flapdoodle-oss/de.flapdoodle.embed.mongo#174] opened 2016-10-19 10:28 UTC
I recently had issue with mentioned exception:

```
java.io.IOException: Cannot run program "/tmp/extract-f77354d0-83fa-47e2-b7e1-47b3577bbf4eextractmongod": error=13, Permission denied`
...
Caused by: java.io.IOException: error=13, Permission denied
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

As I commented [here](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/163#issuecomment-248249887), I thought it's Java version issue.
Unfortunately the issue came back - at least in the  dockerized Jenkins 2.7.4. I never had such problems @ localhost.
The application I'm using embed.mongo for is a custom spring-boot starter (embed.mongo is used in it's tests). Spring boot had version set to latest (**1.50.5**). when I reverted version for my tests to **1.50.3** and purged `~/.embedmongo` directory it started working fine again.

If you need any more info, please let me know.

**Comment by Loki-Afro** [comment] 2017-02-26 21:35
@poznachowski I had once a similar issue with a dockerized build - in the end it was a permission failure where no such file or directory was misleading and the binary was not executeable. 

Can you verify this? 

Can you somehow setup an example project?

**Comment by Loki-Afro** [comment] 2017-03-11 10:43
@poznachowski I will close this issue for now, can't reproduce it.

**Closed by Loki-Afro** 2017-03-11 10:43 UTC

**Comment by rodrigobitlima** [comment] 2017-11-14 17:16
@poznachowski I am having the same problem with a build created using gitLab CI and a embed mongo. You have some news about this issue? 
[log.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/1471839/log.txt)

**Comment by Loki-Afro** [comment] 2017-11-14 19:16
@rodrigobitlima you have to debug that container, when this exception occurs exec into the container and verify the file is there and you have the right permissions, even a file not found could mean you don't have permission to read from that location and even if its in /tmp

**Comment by jeep87c** [comment] 2018-06-20 21:04
@rodrigobittlima we're facing the exact same issue with GitLab CI and latest flapDoodle version 2.0.3. Did you find the root cause? Any help would be much appreciated, we have no clue on this one...

**Comment by Loki-Afro** [comment] 2018-06-20 21:07
hint: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/242

**Comment by jeep87c** [comment] 2018-06-21 13:32
I saw the comments about alpine thing and ensure it's not our case. We still see the issue from time to time in our GitLab CI pipeline. FYI, our pipeline runs our tests using maven and multi-threading.

Here's our docker file:

```
FROM maven:3.5-jdk-8

RUN apt-get update
RUN apt-get install -y gawk

RUN apt-get install -y \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

RUN apt-get update
RUN apt-get install -y docker-ce
```

We are actually facing two different and inconsistent issues (by inconsistent I mean it doesn't fail systematically at each run, it fails from time to time). Here's stacktraces for each:

```
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: could not create: /root/.embedmongo/extracted/Linux-B64--3.2.1/extractmongod
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:69)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at com.bell.cts.commons.mongo.EmbeddedMongoServer.start(EmbeddedMongoServer.java:86)
	at com.bell.cts.commons.mongo.MongoServer.<clinit>(MongoServer.java:22)
	... 19 more
Caused by: de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: could not create: /root/.embedmongo/extracted/Linux-B64--3.2.1/extractmongod
	at de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:125)
	at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:75)
	at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:79)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:57)
	... 22 more
Caused by: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: could not create: /root/.embedmongo/extracted/Linux-B64--3.2.1/extractmongod
	at de.flapdoodle.embed.process.io.file.Files.createTempFile(Files.java:69)
	at de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:123)
	... 26 more
```

```
Caused by: java.lang.IllegalStateException: java.io.IOException: Cannot run program "/tmp/extract-5f4ae67f-d11f-4571-b883-7deb632f8bfeextractmongod": error=13, Permission denied
	at com.bell.cts.commons.mongo.MongoServer.<clinit>(MongoServer.java:26)
	... 19 more
Caused by: java.io.IOException: Cannot run program "/tmp/extract-5f4ae67f-d11f-4571-b883-7deb632f8bfeextractmongod": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at com.bell.cts.commons.mongo.EmbeddedMongoServer.start(EmbeddedMongoServer.java:87)
	at com.bell.cts.commons.mongo.MongoServer.<clinit>(MongoServer.java:22)
	... 19 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 28 more
```

PS: I can open a new issue if you want, just le me know.

**Comment by cakofony** [comment] 2018-06-29 19:52
We're seeing this issue as well:
https://issues.apache.org/jira/browse/LOG4J2-2348

**Comment by jeep87c** [comment] 2018-07-13 19:43
Here's what we did to fix this issue on our side for a multi-threaded test project (both naming methods) :

`new ExtractedArtifactStoreBuilder().defaults(Command.MongoD).executableNaming(new UUIDTempNaming()).extractExecutableNaming(new UUIDTempNaming())`

**Comment by vgindin** [comment] 2018-08-16 08:27
Hi. I've faced with such problem in another project. Could you explain your solution? Why did it help?

**Comment by jeep87c** [comment] 2018-08-16 12:43
@vgindin instead of using UUIDTempNaming() we were using the other option which is not a unique name. Result was flapdoodle running in different threads was trying to create an executable file using the same name causing the exception. Ensuring it use a unique name at each execution like we did, solved the problem.
