### ISSUE TITLE
java.lang.IllegalStateException: Couldn't kill mongod process!

### ISSUE THREAD

**Issue by rajenders** [flapdoodle-oss/de.flapdoodle.embed.mongo#212] opened 2017-09-06 06:45 UTC
I'm using flapdoodle version 2.0 and intermittently I'm getting the below error, please let me know. Thank you. 

Exception: 
----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------

        at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:193)
        at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:77)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:184)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:109)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:165)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:115)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:52)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:99)
        at com.xyz.common.persistence.TestDatabaseFactory.init(TestDatabaseFactory.java:124)
        at com.xyz.common.persistence.TestDatabaseFactory.<init>(TestDatabaseFactory.java:89)
        at com.xyz.common.persistence.TestDatabaseGroup.<init>(TestDatabaseGroup.java:32)
        ... 23 more

**Comment by Loki-Afro** [comment] 2017-09-08 14:33
@rajenders is this the full stacktrace?

**Comment by rajenders** [comment] 2017-09-10 06:23
Thank you @Loki-Afro, that's the full stacktrace I could see.

**Comment by faizan-talena** [comment] 2017-09-18 08:00
I see similar error while running my test case. In my test case I start a bunch of MondoD for configserver and shards, and a MongoS process. I configure these processes so that they are part of one Mongo cluster.

Here are the detailed logs of the test case 

```
[mongos output] 2017-09-18T13:19:53.957+0530 I COMMAND  [conn12] dropDatabase test starting
[mongod output] 2017-09-18T13:19:53.958+0530 I COMMAND  [conn12] dropDatabase test finished
[mongod output] 2017-09-18T13:19:53.961+0530 I COMMAND  [repl writer worker 4] dropDatabase test starting
[mongod output] 2017-09-18T13:19:53.963+0530 I COMMAND  [repl writer worker 4] dropDatabase test finished
[mongod output] 2017-09-18T13:19:53.980+0530 I SHARDING [conn2] about to log metadata event into changelog: { _id: "fkhan-VirtualBox-2017-09-18T13:19:53.979+0530-59bf7aa164f2885f769591d2", server: "fkhan-VirtualBox", clientAddr: "127.0.0.1:55950", time: new Date(1505720993979), what: "dropDatabase", ns: "test", details: {} }
[mongos output] 2017-09-18T13:19:54.009+0530 I SHARDING [conn2] distributed lock with ts: 59bf7aa164f2885f769591d0' unlocked.
[mongos output] 2017-09-18T13:19:54.016+0530 I -        [conn2] end connection 127.0.0.1:55950 (2 connections now open)
[mongos output] Sep 18, 2017 1:19:54 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Closed connection [connectionId{localValue:6}] to 127.0.0.1:37302 because the pool has been closed.
2017-09-18T13:19:54.021+0530 I -        [conn1] end connection 127.0.0.1:55948 (1 connection now open)
[mongos output] 2017-09-18T13:19:54.027+0530 I NETWORK  [thread2] connection accepted from 127.0.0.1:39146 #3 (1 connection now open)
[mongos output] 2017-09-18T13:19:54.119+0530 I -        [conn6] end connection 127.0.0.1:60420 (4 connections now open)
[mongod output] 2017-09-18T13:19:54.119+0530 I -        [conn4] end connection 127.0.0.1:43806 (9 connections now open)
[mongod output] 2017-09-18T13:19:54.119+0530 I -        [conn7] end connection 127.0.0.1:43816 (8 connections now open)
[mongod output] 2017-09-18T13:19:54.120+0530 I -        [conn5] end connection 127.0.0.1:43808 (7 connections now open)
[mongod output] 2017-09-18T13:19:54.120+0530 I -        [conn6] end connection 127.0.0.1:43810 (6 connections now open)
[mongod output] 2017-09-18T13:19:54.115+0530 I COMMAND  [conn3] terminating, shutdown command received
[mongos output] 2017-09-18T13:19:54.116+0530 W SHARDING [conn3] error encountered while cleaning up distributed ping entry for fkhan-VirtualBox:37302:1505720978:-3860625049658001582 :: caused by :: InterruptedAtShutdown: interrupted at shutdown
[mongos output] 2017-09-18T13:19:54.117+0530 I CONTROL  [conn3] shutting down with code:0
[mongos output] 
2017-09-18T13:19:54.119+0530 I -        [conn14] end connection 127.0.0.1:59436 (10 connections now open)
[mongod output] 2017-09-18T13:19:54.119+0530 I -        [conn15] end connection 127.0.0.1:59438 (9 connections now open)
[mongod output] 2017-09-18T13:19:54.119+0530 I -        [conn11] end connection 127.0.0.1:59430 (8 connections now open)
[mongod output] 2017-09-18T13:19:54.120+0530 I -        [conn12] end connection 127.0.0.1:59432 (7 connections now open)
[mongod output] 2017-09-18T13:19:54.120+0530 I -        [conn13] end connection 127.0.0.1:59434 (6 connections now open)
[mongod output] 2017-09-18T13:19:54.276+0530 I NETWORK  [thread1] connection accepted from 127.0.0.1:59442 #16 (6 connections now open)
[mongod output] 2017-09-18T13:19:58.966+0530 I REPL     [replication-1] Restarting oplog query due to error: InterruptedDueToReplStateChange: operation was interrupted. Last fetched optime (with hash): { ts: Timestamp 1505720993000|1002, t: 1 }[7799395596619960400]. Restarts remaining: 3
[mongod output] 2017-09-18T13:19:58.968+0530 I REPL     [replication-1] Scheduled new oplog query Fetcher source: 127.0.1.1:37492 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1505720993000|1002 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1 } query metadata: { $replData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 84 -- target:127.0.1.1:37492 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1505720993000|1002 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1 } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
[mongod output] java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------


	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:192)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:189)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
	at com.talena.agent.mongodb.MongoShardedCluster.stop(MongoShardedCluster.java:285)
	at com.talena.agent.mongodb.TestMongoShardedCluster.tearDownAfterClass(TestMongoShardedCluster.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
2017-09-18T13:19:59.408+0530 I NETWORK  [thread1] connection accepted from 127.0.0.1:60436 #7 (4 connections now open)
[mongod output] 2017-09-18T13:19:59.410+0530 I COMMAND  [conn7] terminating, shutdown command received
[mongod output] 2017-09-18T13:19:59.410+0530 I NETWORK  [conn7] shutdown: going to close listening sockets...
[mongod output] 2017-09-18T13:19:59.410+0530 I NETWORK  [conn7] closing listening socket: 6
[mongod output] 2017-09-18T13:19:59.410+0530 I NETWORK  [conn7] closing listening socket: 7
[mongod output] 2017-09-18T13:19:59.410+0530 I NETWORK  [conn7] removing socket file: /tmp/mongodb-44610.sock
[mongod output] 2017-09-18T13:19:59.410+0530 I NETWORK  [conn7] shutdown: going to flush diaglog...
[mongod output] 2017-09-18T13:19:59.410+0530 I REPL     [conn7] shutting down replication subsystems
[mongod output] 2017-09-18T13:19:59.410+0530 I REPL     [conn7] Stopping replication reporter thread
[mongod output] 2017-09-18T13:19:59.412+0530 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to 127.0.1.1:37492: CallbackCanceled: Reporter no longer valid
[mongod output] 2017-09-18T13:19:59.413+0530 I REPL     [conn7] Stopping replication fetcher thread
[mongod output] 2017-09-18T13:19:59.413+0530 I REPL     [conn7] Stopping replication applier thread
[mongod output] 2017-09-18T13:19:59.421+0530 I REPL     [conn7] Stopping replication storage threads
[mongod output] 2017-09-18T13:19:59.433+0530 W SHARDING [conn7] cant reload ShardRegistry  :: caused by :: CallbackCanceled: Callback canceled
[mongod output] 2017-09-18T13:19:59.433+0530 I FTDC     [conn7] Shutting down full-time diagnostic data capture
[mongod output] 2017-09-18T13:19:59.437+0530 W SHARDING [conn7] error encountered while cleaning up distributed ping entry for fkhan-VirtualBox:44610:1505720992:1279584608307429253 :: caused by :: InterruptedAtShutdown: interrupted at shutdown
[mongod output] 2017-09-18T13:19:59.438+0530 I STORAGE  [conn7] WiredTigerKVEngine shutting down
[mongod output] 2017-09-18T13:19:59.570+0530 I STORAGE  [conn7] shutdown: removing fs lock...
[mongod output] 2017-09-18T13:19:59.570+0530 I CONTROL  [conn7] now exiting
[mongod output] 2017-09-18T13:19:59.570+0530 I CONTROL  [conn7] shutting down with code:0
[mongod output] 2017-09-18T13:19:59.586+0530 I -        [conn10] end connection 127.0.0.1:43840 (5 connections now open)
[mongod output] 2017-09-18T13:19:59.587+0530 I -        [conn11] end connection 127.0.0.1:43842 (4 connections now open)
[mongod output] 2017-09-18T13:19:59.588+0530 I -        [conn12] end connection 127.0.0.1:43844 (3 connections now open)
[mongod output] 
2017-09-18T13:19:59.712+0530 I NETWORK  [thread2] connection accepted from 127.0.0.1:43864 #13 (3 connections now open)
[mongod output] 2017-09-18T13:20:01.360+0530 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to 127.0.1.1:37492
[mongod output] 2017-09-18T13:20:01.362+0530 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Failed to connect to 127.0.1.1:37492 - HostUnreachable: Connection refused
[mongod output] 2017-09-18T13:20:01.363+0530 I NETWORK  [Balancer] Marking host 127.0.1.1:37492 as failed :: caused by :: HostUnreachable: Connection refused
[mongod output] 2017-09-18T13:20:01.865+0530 I NETWORK  [Balancer] Socket closed remotely, no longer connected (idle 13 secs, remote host 127.0.1.1:44610)
[mongod output] 2017-09-18T13:20:01.866+0530 W NETWORK  [Balancer] Failed to connect to 127.0.1.1:44610, in(checking socket for error after poll), reason: Connection refused
[mongod output] 2017-09-18T13:20:01.866+0530 I NETWORK  [Balancer] Marking host 127.0.1.1:44610 as failed :: caused by :: Location40356: connection pool: connect failed 127.0.1.1:44610 : couldn't connect to server 127.0.1.1:44610, connection attempt failed
[mongod output] 2017-09-18T13:20:01.866+0530 W NETWORK  [Balancer] No primary detected for set shard0
[mongod output] 2017-09-18T13:20:01.866+0530 I NETWORK  [Balancer] All nodes for set shard0 are down. This has happened for 1 checks in a row.
[mongod output] java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------


	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:192)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:189)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
	at com.talena.agent.mongodb.MongoShardedCluster.stop(MongoShardedCluster.java:285)
	at com.talena.agent.mongodb.TestMongoShardedCluster.tearDownAfterClass(TestMongoShardedCluster.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

The exception seems to be thrown from AbstractMongoProcess.stopInternal whenever a process takes time to die. This is causing AbstractProcess.cleanupInternal call to be skipped. I see tmp directory bloat every time I run the test.

I could not figure out the code which deletes the tmp files.

**Comment by faizan-talena** [comment] 2017-09-26 10:03
I figured this clean up is not happening due to an issue in embed.process, I filed an issue there https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/61
But that would need upgrade of embed.process version.

Should I fix this by handling exception in AbstractMongoProcess.stopInternal ?

**Comment by rajenders** [comment] 2017-10-12 01:36
Thank you so much @faizan-talena, could fix in stopInternal until next version of embed.process available.

**Comment by xsilmarx** [comment] 2018-03-07 16:27
Not sure if this is the same issue, I started using this lib, version 2.0.3, but if I try to close the MongodExecutable from within the @AfterClass teardown method, the method gets stucked on the close() - see stack trace.
The solution was to not close the MongodExecutable at all, but I'm not sure if this is safe.
Is this the same issue or should I open a new one?

Thread [vert.x-eventloop-thread-0] (Suspended)	
	owns: FileDescriptor  (id=89)	
	owns: MongodProcess  (id=90)	
	owns: MongodExecutable  (id=91)	
	FileInputStream.close0() line: not available [native method]	
	FileInputStream.access$000(FileInputStream) line: 49	
	FileInputStream$1.close() line: 328	
	FileDescriptor.closeAll(Closeable) line: 216	
	FileInputStream.close() line: 326	
	ProcessControl.closeIOAndDestroy() line: 84	
	ProcessControl.stopOrDestroyProcess() line: 121	
	ProcessControl.waitForProcessGotKilled() line: 174	
	ProcessControl.stop() line: 76	
	MongodProcess(AbstractProcess<T,E,P>).stopProcess() line: 196	
	MongodProcess(AbstractMongoProcess<T,E,P>).stopInternal() line: 117	
	MongodProcess(AbstractProcess<T,E,P>).stop() line: 177	
	MongodExecutable(Executable<T,P>).stop() line: 80	
	TestMongoDbClient.teardown() line: 127

**Comment by faizan-talena** [comment] 2018-03-08 06:50
@xsilmarx The problem does not seem to be the same.
You are facing an IO issue, while what @rajenders faced was definitely a timeout issue (Mongo process did not shut down in 3 seconds).
Are you reusing MongodProcess instance across multiple threads ?

**Comment by xsilmarx** [comment] 2018-03-08 14:15
@faizan-talena here's the source code of how I instantiate the embedded MongoDB:

`// start embedded MongoDB
		IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder().defaults(Command.MongoD).daemonProcess(false).build();
		MongodStarter starter = MongodStarter.getInstance(runtimeConfig);

		String bindIp = "localhost";
		int port = 12345;
		IMongodConfig mongodConfig = new MongodConfigBuilder()
			.version(Version.Main.PRODUCTION)
			.net(new Net(bindIp, port, Network.localhostIsIPv6()))
			.build();

		mongodExecutable = starter.prepare(mongodConfig);
		mongodExecutable.start();`

I do this inside the static method that I have annotated with @BeforeClass in my test class, which means, the mongodExecutable is a static variable.

All accesses to the MongoDB instance then are made from the same thread, because I'm using Vert.x and there's a single Verticle interacting with the database.

**Comment by Loki-Afro** [comment] 2018-03-08 14:17
@xsilmarx could you please create a new issue?

**Comment by xsilmarx** [comment] 2018-03-08 14:25
After restarting the computer a couple of times I'm not able to reproduce this error anymore. Maybe it was an intermitent issue with the OS filesystem lock. I will create a new issue in case I'm able to reproduce it again.
Thanks.

**Comment by Loki-Afro** [comment] 2018-04-12 20:30
just mentioning https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/64 maybe it helps some of you

**Comment by benmccann** [comment] 2018-06-29 19:47
This should hopefully be fixed by https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/commit/f5f1505712861297adc7718ab9dd70ed883c89ba

**Closed** 2018-10-07 10:35 UTC

**Comment by davidgfolch** [comment] 2020-05-28 11:35
I'm having this issue in an @SpringBootTest, all processes are killed properly, no one still running.

So I've just put try/catch to avoid tests to finish properly:

```java
    @AfterAll
    public static void end() {
        if (nonNull(mongo))
            mongo.close();
        if (nonNull(mongod))
            try {
                mongod.stop();
            } catch (IllegalStateException e) {
                log.error("Can't stop mongod",e);
            }
        if (nonNull(mongodExecutable))
            try {
                mongodExecutable.stop();
            } catch (IllegalStateException e) {
                log.error("Can't stop mongodExecutable",e);
            }
    }
```

**log:**
```
[DEBUG] org.springframework.data.mongodb.MongoTransactionManager - About to commit transaction for session [ClientSessionImpl@7c045627 id = {"id": {"$binary": "h6+HSRYYRS6mBQm7oBADaA==", "$type": "04"}}, causallyConsistent = true, txActive = true, txNumber = 7, error = d != java.lang.Boolean].
[DEBUG] org.springframework.data.mongodb.MongoTransactionManager - About to release Session [ClientSessionImpl@7c045627 id = {"id": {"$binary": "h6+HSRYYRS6mBQm7oBADaA==", "$type": "04"}}, causallyConsistent = true, txActive = false, txNumber = 7, error = d != java.lang.Boolean] after transaction.
[INFO] net.energytools.ambar.ApplicationIT - Started ApplicationIT in 33.732 seconds (JVM running for 44.523)

2020-05-28T13:30:06.610+0200 I NETWORK  [conn2] end connection 127.0.0.1:39020 (5 connections now open)
[mongod output] 2020-05-28T13:30:06.611+0200 I NETWORK  [conn1] end connection 127.0.0.1:39018 (4 connections now open)
[mongod output] [DEBUG] de.flapdoodle.embed.mongo.AbstractMongoProcess - try to stop mongod
2020-05-28T13:30:06.621+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:39050 #14 (5 connections now open)
[mongod output] [ERROR] net.energytools.ambar.ApplicationIT - Can't stop mongod
java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------


	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:200)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:196)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:177)
	at net.energytools.ambar.ApplicationIT.end(ApplicationIT.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:111)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterAllMethod(TimeoutExtension.java:102)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$10(ClassBasedTestDescriptor.java:399)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$11(ClassBasedTestDescriptor.java:397)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllMethods(ClassBasedTestDescriptor.java:397)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:209)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
[DEBUG] org.springframework.web.context.support.GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@372b0d86, started on Thu May 28 13:29:33 CEST 2020
[WARN] org.mongodb.driver.connection - Got socket exception on connection [connectionId{localValue:6, serverValue:13}] to localhost:27117. All connections to localhost:27117 will be closed.
[INFO] net.energytools.ambar.service.util.AmbarDBFetchControlService$StackPool - Destroyed resource pool {}
[DEBUG] de.flapdoodle.embed.mongo.AbstractMongoProcess - try to stop mongod
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.880+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:39536 #1 (1 connection now open)
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.880+0200 I COMMAND  [conn1] terminating, shutdown command received
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I NETWORK  [conn1] shutdown: going to close listening sockets...
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I NETWORK  [conn1] closing listening socket: 7
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I NETWORK  [conn1] closing listening socket: 8
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I NETWORK  [conn1] removing socket file: /tmp/mongodb-44529.sock
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I NETWORK  [conn1] shutdown: going to flush diaglog...
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.881+0200 I FTDC     [conn1] Shutting down full-time diagnostic data capture
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:16.883+0200 I STORAGE  [conn1] WiredTigerKVEngine shutting down
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:17.228+0200 I STORAGE  [conn1] shutdown: removing fs lock...
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:17.228+0200 I CONTROL  [conn1] now exiting
[INFO] org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo - 2020-05-28T13:30:17.229+0200 I CONTROL  [conn1] shutting down with code:0

Process finished with exit code 0
```

**Comment by shilpauran** [comment] 2020-09-18 15:23
better way is as below :
its because the process takes a few seconds to shutdown. so do an await for a few seconds and then let the process stop. below is the java code for the same. keep in mind that process and executable are already created. this is just to stop the mongoDb
import static org.awaitility.Awaitility.await;
public void stopMongoDb() throws IOException {
if (process != null) {
try {
process.stop();
} catch (IllegalStateException e) {
if (process != null) {
await().atMost(1, TimeUnit.MINUTES).until(() -> !process.isProcessRunning());
} else {
throw new IllegalStateException(e);
}
}
}
if (mongodExecutable != null) {
mongodExecutable.stop();
}
}

in the above code, if the process is still running then the method isProcessRunning() returns true. we wait until it is false, or we wait until 1 min is over.
