### ISSUE TITLE
java.io.IOException: Could not open inputStream Server returned HTTP response code: 403

### ISSUE THREAD

**Issue by MUsman1992** [flapdoodle-oss/de.flapdoodle.embed.mongo#447] opened 2023-01-28 01:46 UTC
I have started working on a project in which Flapdoodle Embedded MongoDB is used for test cases. When my application tries to download the database, I get the following error:

```
2023-01-28 02:43:13,653 [34mINFO [0;39m [36mo.m.d.connection@[main][0;39m - Opened connection [connectionId{localValue:6, serverValue:87}] to localhost:27017
Download GenericFeatureAwareVersion{5.0.2}:Platform{operatingSystem=Windows, architecture=X86_64} START
2023-01-28 02:43:14,104 [1;31mERROR[0;39m [36md.f.e.p.r.Starter@[main][0;39m - prepare executable
java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-{tools.version}.zip with proxy Optional.empty
	at de.flapdoodle.embed.process.store.UrlConnectionDownloader.downloadInputStream(UrlConnectionDownloader.java:137)
	at de.flapdoodle.embed.process.store.UrlConnectionDownloader.download(UrlConnectionDownloader.java:72)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:74)
	at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:79)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.jsonArrayImport(EmbeddedMongo.java:842)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.importToCollection(EmbeddedMongo.java:722)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.lambda$importTestData$4(EmbeddedMongo.java:671)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.importTestData(EmbeddedMongo.java:674)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.lambda$importTestData$3(EmbeddedMongo.java:654)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.EmbeddedMongo.importTestData(EmbeddedMongo.java:647)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.rule.EmbeddedMongoRule.importData(EmbeddedMongoRule.java:57)
	at com.airbus.ds.rangedb.rest.commons.mongo.test.rule.EmbeddedMongoRule.startup(EmbeddedMongoRule.java:82)
	at com.airbus.ds.rangedb.rest.commons.model.mongo.rule.EmbeddedMongoClientRule.startup(EmbeddedMongoClientRule.java:45)
	at com.airbus.ds.rangedb.rest.commons.test.rule.CombinedRule$2.evaluate(CombinedRule.java:31)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-{tools.version}.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at de.flapdoodle.embed.process.store.UrlConnectionDownloader.downloadInputStream(UrlConnectionDownloader.java:133)
	... 57 common frames omitted



```

I am using the following technologies:

Java version: 11
Mongodb version: 5.0.2
spring boot version: 2.6.1
Flapdoodle Embedded MongoDB version: 3.3.1
Besides this, my system has  a x64-based processor.

I have also checked this issue https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/377 and after that, I have also tried to update the version of Flapdoodle Embedded MongoDB and I tried to upgrade it to 3.4.3 but still I am facing the same issue. Can anybody guide me how to fix it? Thanks

**Comment by michaelmosmann** [comment] 2023-01-28 17:15
@MUsman1992 please use this spring integration: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x as flapdoodle mongodb <4.x.x is in maintenance mode now.. 

please be careful to exclude the old mongodb-version to avoid confusing error messages..

**Comment by MUsman1992** [comment] 2023-01-30 10:46
@michaelmosmann thanks for your reply. Right now, I am working on the project that has been already built by someone else. that's why right now it's not easy for me to change the libraries. What I have figured out that my code is able to download MongoDB database but it is unable to download MongoDB tools because in this url https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-{tools.version}.zip tools version is not set. Can you tell me how I can set the version of the MongoDB tools in the code. The MongoDB version is set in my project using the following code:
```
private static IFeatureAwareVersion createVersion() {
        final var features = new Feature[]{Feature.NO_HTTP_INTERFACE_ARG, Feature.NO_CHUNKSIZE_ARG};
        return Versions.withFeatures(Version.of("5.0.2"), features);
}
```
Right now, I have manually downloaded MongoDB tools and provided the path in the code in order to skip this download step so that my code runs successfully.

Can you guide me how I can set the MongoDB tools version in my code in order to avoid this. Thanks

**Comment by michaelmosmann** [comment] 2023-01-30 13:57
@MUsman1992 hmm.. this is a hard one.. this is one of the issues why did a mayor refactoring and even wrote my own spring integration. It will take some time to reproduce your problem and even fix this in the legacy version of this library..  i would suggest to just change the spring integration. This problem is maybe not the last one..

But i do understand that this is maybe not an available option.

In the meantime you can try to increment the version of embedded mongodb above 3.3.1 until you will get some class mismatch stuff (version must be <4.0.0) .. maybe your problem can be solved this way (i do not remember in which version the api changed to much)

**Comment by michaelmosmann** [comment] 2023-01-31 07:11
@MUsman1992 ah.. ok. So yes.. now it is obvious for me:) So even i can not remember all the edge cases and workarounds anymore:) ..

If you have any spare time i would suggest to update this to the latest version:)

should we close this issue?

**Comment by MUsman1992** [comment] 2023-02-01 16:32
@michaelmosmann thanks for the reply and suggestion. I just have one more question and after that, we can close this issue. Previously as I have told you above that I was using the below code previously: 

```
private static IFeatureAwareVersion createVersion() {
        final var features = new Feature[]{Feature.NO_HTTP_INTERFACE_ARG, Feature.NO_CHUNKSIZE_ARG};
       return new GenericFeatureAwareVersionWithTools(de.flapdoodle.embed.mongo.distribution.Version.V5_0_2, MongotoolsVersion.Main.V100_5, features);
 }

```

Now I have also added this code
```
private static IFeatureAwareVersion createMongoDBDatabaseToolsVersion() {
    	return de.flapdoodle.embed.mongo.distribution.Version.V5_0_2;
}

```

As you can see that in the enum, de.flapdoodle.embed.mongo.distribution.Version.V5_0_2 there are more feature. Can the addition of more features affect anything? Can you guide me in this regard? Thanks

<img width="1128" alt="flapdoodle_code" src="https://user-images.githubusercontent.com/62036653/216103615-6863563e-1832-42d6-8397-4b54863c8c69.png">

**Comment by michaelmosmann** [comment] 2023-02-02 10:32
@MUsman1992 I little bit about what looks like features: The mongodb you choose has some features or not..  you can not enable or disable a feature .. some command line arguments are only enabled if the underlying mongodb has a specific feature.. so it was never intended that you can enable or disable a feature as a library user .. 

Maybe this code explains it a little: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/main/java/de/flapdoodle/embed/mongo/packageresolver/DefaultFeatureSetResolver.java

**Comment by michaelmosmann** [comment] 2023-02-08 06:14
@MUsman1992 is there anything left to do or should we close this issue?

**Comment by MUsman1992** [comment] 2023-02-08 10:34
@michaelmosmann yes we can close it now. Thanks

**Closed** 2023-02-08 16:04 UTC
Labels: waiting_for_reply, spring-integration-problem
