### ISSUE TITLE
java.lang.IncompatibleClassChangeError while initiating [de.flapdoodle.embed.mongo.MongodExecutable]

### ISSUE THREAD

**Issue by zcxsythenew** [flapdoodle-oss/de.flapdoodle.embed.mongo#427] opened 2022-10-17 08:36 UTC
After upgrading de.flapdoodle.embed.mongo from 3.4.11 to 3.5.0, an error was occurred before running test cases:
```text
40:45.124 WARN  [main        ] o.s.w.c.s.GenericWebApplicationContext.refresh:591           - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'xxx.xxxxxx.xxx': Unsatisfied dependency expressed through field 'mongoTemplate';
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0;
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0;
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed;
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception;
nested exception is java.lang.IncompatibleClassChangeError: Found interface de.flapdoodle.os.Platform, but class was expected
```

**Comment by hivenet-mdevarasetty-osi** [comment] 2022-10-17 09:35
We are also facing same issue without any change in the version upgrade.de.flapdoodle.embed.mongo is 3.4.6 version.

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is java.lang.IncompatibleClassChangeError: Found interface de.flapdoodle.os.Platform, but class was expected`

**Comment by hivenet-mdevarasetty-osi** [comment] 2022-10-17 09:47
@zcxsythenew issue fixed for me after upgrading versions as below:

de.flapdoodle.embed.mongo --> 3.5.0
de.flapdoodle.embed.process --> 3.2.0

**Comment by michaelmosmann** [comment] 2022-10-17 13:36
@zcxsythenew  de.flapdoodle.embed.mongo comes with de.flapdoodle.embed.process:3.2.0 .. so you don't need to declare this dependency by yourself..

**Comment by yadavan88** [comment] 2022-10-17 14:38
I am also facing a similar issue out of nowhere. I am getting the exception as "Found interface de.flapdoodle.os.Platform, but class was expected". When I went and looked at this file from flapdoodle-os, I found that it was changed from Interface to abstract class. Upgrading the flapdoodle embed mongo version didn't help me.

**Comment by yadavan88** [comment] 2022-10-17 15:06
My apologies, upgrading to 3.5.0 version did fix the issue for me.

**Comment by michaelmosmann** [comment] 2022-10-17 16:26
@yadavan88 in the end it could be solved:) so i close this issue..

**Closed by michaelmosmann** 2022-10-17 16:26 UTC

**Comment by narugoyal** [comment] 2022-10-18 11:38
For me, issue suddenly started happening on spring boot 2.7.1 without any change in libraries.
And as a fix, I upgraded to latest spring boot 2.7.4

**Comment by santik** [comment] 2022-10-18 12:29
I have the same issue
Caused by: java.lang.IncompatibleClassChangeError: Found interface de.flapdoodle.os.Platform, but class was expected
Using SpringBoot 2.7.4 and de.flapdoodle.embed.mongo 3.5.0
I tried to put spring.mongodb.embedded.version=5.0.0 into properties
No luck.

**Comment by yadavan88** [comment] 2022-10-18 12:33
@santik 
Does the Platform show as Interface or abstract class? With the latest version of embedded-mongo library, it pulls flapdoodle-os as transitive dependency. The platform change is in this library.

**Comment by yadavan88** [comment] 2022-10-18 12:36
@michaelmosmann Just asking this due to my curiosity. Any idea why the change got affected without the version update? By any chance, the flapdoodle-os latest changes got published with the same version? I was just trying to understand how this behaviour. 
Thanks in advance!

**Comment by santik** [comment] 2022-10-18 13:44
> Does the Platform show as Interface or abstract class

@yadavan88 an abstract class. It takes it from flapdoodle.os-1.2.1.jar

**Comment by michaelmosmann** [comment] 2022-10-18 21:46
sorry for this.. the change was in flapdoodle-os .. and i am not sure if i did choose the right sem-ver for this..
